# Auto Trading System Configuration

# Trading Settings
trading:
  mode: "backtest"  # backtest, live, paper
  symbols: ["Bitstamp:BTCUSD"] # ["VHC.VN"] # ["Bitstamp:BTCUSD"]
  initial_capital: 100000
  commission: 0.001  # 0.1% commission per trade
  
# Data Settings
data:
  source: "tradingview"  # yfinance, vnstock, custom, tradingview
  start_date: "2023-01-01"
  end_date: "2025-07-31"
  interval: "4h"  # 1d, 1h, 2h, 3h, 4h, 1m, 3m, 5m, 15m, 30m, 45m, monthly, weekly
  cache_data: true
  cache_dir: "data/cache"
  n_bars: 100

# Risk Management
risk:
  max_position_size: 0.2  # 20% of portfolio per position
  max_portfolio_risk: 0.05  # 5% max portfolio risk
  stop_loss: 0.05  # 5% stop loss
  take_profit: 0.15  # 15% take profit
  max_drawdown: 0.20  # 20% max drawdown

# Strategy Settings
strategies:
  sma_crossover:
    short_window: 5
    long_window: 30
    enabled: true
    
  rsi:
    period: 20
    oversold: 30
    overbought: 70
    enabled: false
    
  macd:
    fast_period: 15
    slow_period: 20
    signal_period: 7
    enabled: false

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/trading.log"
  max_size: "10MB"
  backup_count: 5

# Database
database:
  url: "sqlite:///data/trading.db"
  echo: false

# Dashboard
dashboard:
  host: "0.0.0.0"
  port: 5000
  debug: false

# API Keys (for live trading)
api_keys:
  alpha_vantage: ""
  alpaca_key: ""
  alpaca_secret: ""
  alpaca_base_url: "https://paper-api.alpaca.markets"  # Use paper trading URL 